name: Keep Render Alive

on:
  schedule:
    # Dispara a cada 10 minutos
    - cron: '*/10 * * * *'
  workflow_dispatch: # Permite que você teste manualmente se quiser

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Render URL
        run: curl -I https://carona-api-0gnb.onrender.com
